services:
  claude-code:
    build: .
    container_name: claude-code
    hostname: claude-code
    environment:
      - LANG=en_GB.UTF-8
      - LANGUAGE=en_GB:en
      - LC_ALL=en_GB.UTF-8
    volumes:
      # Persist Claude Code configuration
      - claude-config:/home/jamie/.config/claude-code
      # Persist code-server configuration
      - code-server-config:/home/jamie/.config/code-server
      # Mount any project directories as needed, e.g.:
      # - /path/to/project:/home/jamie/project
    networks:
      - openshaw-services
    ports:
      - "127.0.0.1:8443:8443"  # Only expose locally
    working_dir: /home/jamie
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  claude-config:
    driver: local
  code-server-config:
    driver: local

networks:
  openshaw-services:
    external: true